### PR TITLE
V5 ga 52 global filters editor

### PR DESCRIPTION
**Pull request by SrdjanReblaze**
image
image

### CODE REVIEW

**Review by Aviv-Galmidi — CHANGES_REQUESTED** [review]
1. Active checkbox isn't saved

https://github.com/reblaze/ui/assets/10487148/fb5e68e3-7262-4d89-b1cd-db5b346fee95

2. Button were not converted

Screen Shot 2023-05-10 at 11 22 22
Screen Shot 2023-05-10 at 11 22 46

**Review by Aviv-Galmidi — COMMENTED** [review]
Dropdown menu button itself was not converted still
Screen Shot 2023-05-18 at 13 19 18


Screen Shot 2023-05-18 at 13 19 53

**Comment by SrdjanReblaze** [comment]
> Dropdown menu button itself was not converted still Screen Shot 2023-05-18 at 13 19 18
> 
> Screen Shot 2023-05-18 at 13 19 53

done

**Comment by SrdjanReblaze** [comment]
all comments fixed

**Review by Aviv-Galmidi — APPROVED** [review]

**Pull request merged**
