### PR TITLE
V5 ga 14 menu dropdown

### PR DESCRIPTION
**Pull request by SrdjanReblaze**
https://reblaze.atlassian.net/jira/software/projects/V5GA/boards/39?selectedIssue=V5GA-14

### CODE REVIEW

**Review by Aviv-Galmidi — CHANGES_REQUESTED** [review]
1. The design for the list items doesn't match figma

Screen Shot 2023-03-29 at 10 00 23
Screen Shot 2023-03-29 at 10 00 12

2. The design for the disabled dropdown border doesn't match figma

Screen Shot 2023-03-29 at 10 04 17
Screen Shot 2023-03-29 at 10 04 14


3. Cursor should be pointer when hovering on clickable elements (Menu items)

4. When clicking on selected menu item in multiselect, it should cancel the selection

5. Multiselect is missing checkboxes

6. Multiselect tag hover doesn't look the same

Screen Shot 2023-03-29 at 10 08 09
Screen Shot 2023-03-29 at 10 08 04

**Comment by ljubebiza** [comment]
Done

**Comment by Aviv-Galmidi** [comment]
1. Dropdown goes over the input, in figma it's behind it

Screen Shot 2023-04-04 at 20 47 46

2. There's some weird space under the dropdown when focused

https://user-images.githubusercontent.com/10487148/229876364-c7b680e3-f536-4159-b042-b9788b1dbe66.mov

3. Dropdown header has two borders

Screen Shot 2023-04-04 at 20 47 52

4. Highlighted row doesn't extend to the entire row (right side isn't blue like the rest of the row)

Screen Shot 2023-04-04 at 20 47 59

5. Multiple selection goes out of bounds of the dropdown header

Screen Shot 2023-04-04 at 20 49 21

**Comment by ljubebiza** [comment]
Done, there was problem with DropdownTrigger component that we don't use

**Review by Aviv-Galmidi — CHANGES_REQUESTED** [review]
1. The dropdown arrow isn't vertically aligned to the center

Screen Shot 2023-04-16 at 18 03 27
Screen Shot 2023-04-16 at 18 02 00

2. An error is thrown when clicking on the selected item

https://user-images.githubusercontent.com/10487148/232321959-7c3185f4-1afd-48df-a3a2-923f726d5d0d.mov

3. Border radius changes when hovering on the dropdown

https://user-images.githubusercontent.com/10487148/232322083-19f0f068-b82b-4c69-9683-0e8fe4cc3f9a.mov

4. Clicking `All` selector in multi selector causes the filter to be ignored


https://user-images.githubusercontent.com/10487148/232322189-291094c3-8da9-4000-9884-73e7aa6d16ba.mov

5. Height of selector box changes when empty or with items selected

https://user-images.githubusercontent.com/10487148/232322394-d660e6da-57f9-4d10-a34d-e2f1ff77a1b5.mov

**Comment by Aviv-Galmidi** [comment]
#5 from the previous comment still occurs

**Review by Aviv-Galmidi — APPROVED** [review]

**Pull request merged**
